"""Publish a freshly built openbro.gguf.

Stage 6 of the pipeline:

1. Backup the previous live model.
2. Replace the live `models/openbro.gguf`.
3. Commit + push to the openbro-model git repo (Git LFS for the GGUF).
4. Create a PR via the `gh` CLI.
5. Push to HuggingFace Hub for end-user distribution.

Each step is best-effort + idempotent. If any step fails, the live
model has already been replaced — the rest is purely for distribution.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path


@dataclass
class PublishConfig:
    gguf_path: str
    run_id: str
    repo_dir: str  # local checkout of brijeshch8482/openbro-model
    repo_branch: str = "auto-update"
    pr_title: str = ""
    pr_body: str = ""
    hf_repo_id: str = "brijeshch8482/openbro-1b-instruct"
    skip_pr: bool = False
    skip_hf: bool = False


def _run(cmd: list[str], cwd: str | None = None) -> tuple[int, str, str]:
    """Run a command, capture stdout + stderr, return (code, out, err)."""
    p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return p.returncode, p.stdout, p.stderr


def commit_and_push_to_repo(config: PublishConfig, gguf_path: Path) -> dict[str, object]:
    """Copy openbro.gguf into the model repo, commit with Git LFS,
    push to the auto-update branch."""
    repo_dir = Path(config.repo_dir)
    if not repo_dir.exists():
        raise FileNotFoundError(
            f"Model repo not at {repo_dir}. Clone it first: "
            f"`git clone https://github.com/brijeshch8482/openbro-model "
            f"{repo_dir}` and run `git lfs install` inside it."
        )

    branch = f"{config.repo_branch}-{config.run_id}"
    _run(["git", "checkout", "main"], cwd=str(repo_dir))
    _run(["git", "pull", "--ff-only", "origin", "main"], cwd=str(repo_dir))
    _run(["git", "checkout", "-B", branch], cwd=str(repo_dir))

    dest = repo_dir / "openbro.gguf"
    shutil.copy2(str(gguf_path), str(dest))

    _run(["git", "lfs", "track", "*.gguf"], cwd=str(repo_dir))
    _run(["git", "add", ".gitattributes", "openbro.gguf"], cwd=str(repo_dir))
    code, _, _ = _run(
        ["git", "commit", "-m", f"chore: openbro.gguf {config.run_id}"],
        cwd=str(repo_dir),
    )
    push_code, _, push_err = _run(["git", "push", "origin", branch], cwd=str(repo_dir))

    return {
        "branch": branch,
        "commit_code": code,
        "push_code": push_code,
        "push_err": push_err[:500] if push_err else "",
    }


def create_pull_request(config: PublishConfig, branch: str) -> dict[str, object]:
    """Open a PR via `gh pr create`. Best-effort — returns the PR URL
    on success, or the error output on failure."""
    if config.skip_pr:
        return {"skipped": True}
    title = config.pr_title or f"Auto-update: openbro.gguf {config.run_id}"
    body = config.pr_body or (
        f"Automated training run {config.run_id}.\n\n"
        f"Triggered manually via `openbro train`.\n"
        f"Generated by openbro.training pipeline."
    )
    code, out, err = _run(
        [
            "gh",
            "pr",
            "create",
            "--head",
            branch,
            "--title",
            title,
            "--body",
            body,
        ],
        cwd=str(config.repo_dir),
    )
    return {
        "code": code,
        "url": out.strip() if code == 0 else "",
        "err": err[:500] if err else "",
    }


def push_to_huggingface(config: PublishConfig, gguf_path: Path) -> dict[str, object]:
    """Upload openbro.gguf to HuggingFace Hub so end users can pull
    via `openbro model update`. Requires HF_TOKEN in env or that
    `huggingface-cli login` has already run."""
    if config.skip_hf:
        return {"skipped": True}
    try:
        from huggingface_hub import HfApi
    except ImportError:
        return {"err": "huggingface_hub not installed"}

    api = HfApi()
    try:
        api.upload_file(
            path_or_fileobj=str(gguf_path),
            path_in_repo="openbro.gguf",
            repo_id=config.hf_repo_id,
            commit_message=f"openbro.gguf {config.run_id}",
        )
    except Exception as e:
        return {"err": f"{type(e).__name__}: {e}"}
    return {
        "repo": config.hf_repo_id,
        "uploaded_at": time.time(),
    }


def publish(config: PublishConfig) -> dict[str, object]:
    """Run the full publish pipeline. Each stage is best-effort —
    failure in one doesn't abort the others (e.g. HF push can succeed
    even if the PR fails)."""
    gguf_path = Path(config.gguf_path)
    if not gguf_path.exists():
        return {"err": f"GGUF not found at {gguf_path}"}

    repo_push = commit_and_push_to_repo(config, gguf_path)
    pr = (
        create_pull_request(config, repo_push["branch"])
        if repo_push.get("push_code") == 0
        else {"skipped": "push_failed"}
    )
    hf = push_to_huggingface(config, gguf_path)

    result = {
        "run_id": config.run_id,
        "gguf_path": str(gguf_path),
        "repo_push": repo_push,
        "pr": pr,
        "hf": hf,
    }
    out_dir = gguf_path.parent
    (out_dir / "publish_summary.json").write_text(json.dumps(result, indent=2))
    return result
